spring.application.name=myproject
# server part 변경
server.port= 9090
# DB 연결 url
spring.datasource.url= jdbc:mysql://localhost:3306/mysite
# DB 사용자 아이디
spring.datasource.username= root
# DB 사용자 비밀번호
spring.datasource.password= 1234
# Hibernate의 DDL(Data Definition Language) 자동 생성 설정
spring.jpa.hibernate.ddl-auto=update
# Hiernate SQL 쿼리 콘솔에 출력
spring.jpa.show-sql=true
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE
#file upload 경로 관리
file.upload-dir=C:/upload/
# Security 기본 아이디 비밀번호 설정
spring.security.user.name=admin
spring.security.user.password=1234